### ISSUE TITLE
Convert to a manual workflow for maintaining swagger.yaml

### ISSUE THREAD

**Issue by enobayram** [kadena-io/signing-api#23]
Currently, [the `swagger.yaml` we have in the repo](https://github.com/kadena-io/signing-api/blob/d7078e643a7f4fd944469e264b67540491be070d/swagger.yaml) is not up to date with the changes in the signing API introduced in the last few months, in particular [kip-0015](https://github.com/kadena-io/KIPs/blob/master/kip-0015.md) isn't reflected in it.

I've looked into updating the `kadena-signing-api-docs` Haskell package to compile with the latest `signing-api` type, but it's sort of a rabbit hole at this point, because:
* For example [the new QuickSingResponse JSON schema](https://github.com/kadena-io/KIPs/blob/master/kip-0015.md#quicksign-response) isn't representable accurately as a Swagger 2 schema, so we'd need to upgrade to [the `openapi3` package](https://hackage.haskell.org/package/openapi3) in `kadena-signing-api-docs` and that requires a lot of changes.
* Most of [the types in the kadena signing API](https://github.com/kadena-io/signing-api/blob/d7078e643a7f4fd944469e264b67540491be070d/kadena-signing-api/src/Kadena/SigningTypes.hs) have manually written `To/FromJSON` instances, so the corresponding `ToSchema` definitions in `kadena-signing-api-docs` have to be written manually as well and that point, there isn't much type-safety left because the manual schema definition retains very little connection to the underlying Haskell types.

That's why my suggestion in this ticket is to remove `kadena-signing-api-docs` and convert the maintenance of `swagger.yaml` via a manual workflow. In this workflow, we'd be modifying the spec manually, but we'd put CI actions in place that verify a certain amount of alignment between the spec and the server. I suggest:
* Implementing a new `kadena-signing-api-mock` Haskell package that builds a mock server for [the signing API Haskell type](https://github.com/kadena-io/signing-api/blob/d7078e643a7f4fd944469e264b67540491be070d/kadena-signing-api/src/Kadena/SigningApi.hs#L101-L103) using [`servant-mock`](https://hackage.haskell.org/package/servant-mock). Note that unlike `servant-swagger` (or `servant-openapi3` that we'd use for generating an OAS 3 spec), a mock server shouldn't require any manual definitions, so it's more type safe anyway.
* Implementing a GitHub action that spins up the mock server and uses [Dredd](https://dredd.org/en/latest/) (or another tool like it) to verify the spec against it.
* Implementing another GitHub action that runs an OAS 3 spec validator like the [`swagger-cli`](https://apitools.dev/swagger-cli/) and/or a linter like [`spectral`](https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules).

**Comment by alber70g** [comment]
Sounds like a plan. This way we get up-to-date _valid_ swagger docs, which is the most important thing at this moment.

1. Is it correct to assume that chainweaver relies on these types as well? Is there any concern with respect to chainweaver?
1. I assume the walletbuilders that want to build on the signing-api spec want to use the OpenAPI spec as well. This is still possible, correct?

**Comment by enobayram** [comment]
> Is there any concern with respect to chainweaver?

There shouldn't be any issue in regards to `chainweaver`, it doesn't depend on the `kadena-signing-api-docs` package at all, nobody does. AFAICT its only purpose was to be run once to generate the API spec. If we're switching to manual maintenance of the spec, then there's no reason for `kadena-signing-api-docs` to exist. Note that `kadena-signing-api` will still be there and `chainweaver` will still use the types in it and so will the mock server using `servant-mock` I've mentioned.

> I assume the walletbuilders that want to build on the signing-api spec want to use the OpenAPI spec as well.

I assume so too and that change shouldn't in any way impede that. They can use the manually maintained `swagger.yaml` to validate their implementation or if it so happens that they're building it with Haskell, they can even still use the Haskell types from the `kadena-signing-api` package just like `chainweaver` was and will be doing.

**Comment by jwiegley** [comment]
I'm all in favor of this becoming an as-needed manual process.
